assoc: dynamodb,czbiohub-reflow-quickstart
cluster: ec2cluster
ec2cluster:
  securitygroup: sg-661d7f19
  region: us-west-2
  disktype: gp2
  diskspace: 2500
  diskslices: 0
  ami: ami-4296ec3a
  maxinstances: 25
  instancetypes:
  - c1.medium
  - c1.xlarge
  - c3.2xlarge
  - c3.4xlarge
  - c3.8xlarge
  - c3.large
  - c3.xlarge
  - c4.2xlarge
  - c4.4xlarge
  - c4.8xlarge
  - c4.large
  - c4.xlarge
  - c5.large
  - c5.xlarge
  - c5.2xlarge
  - c5.4xlarge
  - c5.9xlarge
  - c5.18xlarge
  - cc2.8xlarge
  - m1.large
  - m1.medium
  - m1.small
  - m1.xlarge
  - m2.2xlarge
  - m2.4xlarge
  - m2.xlarge
  - m3.2xlarge
  - m3.large
  - m3.medium
  - m3.xlarge
  - m4.16xlarge
  - m4.4xlarge
  - m4.xlarge
  - r4.xlarge
  - t1.micro
  - t2.large
  - t2.medium
  - t2.micro
  - t2.nano
  - t2.small
  sshkey: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCa/3Zq5JUnnkPWAV2xkFbW6qXG1lsiNwymO1Yc2IAZ4eOQmCwlKnXa3+jeTTVvdP760Pg2Uxl3eRUDy4xRXqnHK5ZhxZ/BFEJpMyGZugD7vxAaUrpTfrDNXAARqSCx8UREdZ+jqQdTgYZcdQ/XkXq5JzepnHYK1nGpUToI4qx9cBnszBGL5lMMMlNCbMjQY0JNBkX1UuxUcCftVpQJ3oWa5PoxGnIA1R07n0EMSYT61aMgM3xGzCmEeN+IwsJpS4FlkUlxAHFS4EmAoX1qhM890HTe5sg66xTJ8wM4Fy1cudWkOiiLnxnLcxEKJfgL9DjgOWekN4HsqOvorpkCvkBx ubuntu@ip-172-31-7-88
  keyname: ""
  cloudconfig: {}
https: httpsca,/home/ubuntu/.reflow/reflow.pem
repository: s3,czbiohub-reflow-quickstart-cache
user: local,lincoln-harris.reflow@localhost
repository: s3,czbiohub-reflow-quickstart-cache
assoc: dynamodb,czbiohub-reflow-quickstart
user: local,lincoln-harris.reflow@localhost
