# Makefile
# author: Lincoln Harris
# date: 4.1.18

run1:
	python3 fusionSearchTool.py 1 ALK

run2:
	python3 fusionSearchTool.py 1 EML4

run3:
	python3 fusionSearchTool.py 1 ROS1

run4:
	python3 fusionSearchTool.py 1 RET

run5:
	python3 fusionSearchTool.py 1 NTRK

run6:
	python3 fusionSearchTool.py 0 ALK--EML4


